---
output: github_document
always_allow_html: yes
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# Duke FINTECH Trading Competition 2022
The Duke FINTECH Trading Competition is a free competition hosted by the [FINTECH Program at Duke University](https://fintech.meng.duke.edu/).

The Competition is open to any currently enrolled graduate or undergraduate
student so long as they have an email address with a .edu extension. 

Participating students are issued $1 million in simulated currency within a
paper trading account provided by [Interactive Brokers](https://www.interactivebrokers.com/en/index.php?f=1338&gclid=CjwKCAjw6fCCBhBNEiwAem5SO84OkMDwq8mlx6lCjOmAmCNDUaLbhxtQuFSUlozy6iLEZtmsve2w-hoCQ9sQAvD_BwE).
Students will have the opportunity to trade equities, fxed income, derivatives,
ETFs, cryptocurrencies, and more, all based on real-time streaming market data
using the same user interface and features utilized by professional traders.

The FINTECH program at Duke is inclusive and welcoming. Participation is welcome
and encouraged, so please help spread the word! Standings for the top 10 traders
will be posted here and updated daily as data become available. This site will
continue to grow as new features are brought onboard so be sure to check back
often for updates!!!

# Prizes
As is fitting for this competition prizes will be awarded in USD and ZEN
cryptocurrency, provided by our sponsors! All prizes will be awarded 1/3 ZEN and
2/3 USD.

##### 1st Prize is $3,000
##### 2nd Prize is $2,000
##### 3rd Prize is $1,250
##### 4th Prize is $750
##### 5th Prize is $500


# Registration
Currently enrolled graduate or undergraduate students with a .edu address may
register for the competition by following these steps:

1. Visit the [registration page](https://dukefinance.wufoo.com/forms/2022-duke-fintech-trading-competition/)  
and provide the requested information using your .edu email. 
    - You'll be asked for a trader username -- choose wisely! You may use your
    real name if you want, but understand that when daily standings and
    performance updates are pushed to the website, this is the name that will
    appear to the world alongside your school, department, and username.
2. Within one business day, you'll receive two emails:
    - A welcome email from Duke FINTECH including an invitation to the official
    trading competition Slack channel
    - An invitation email from Interactive Brokers (IBKR) for creating a new
    paper trading account
3. Join the Slack channel
4. Follow the link in your IBKR invitation email and fill out the application
for a new paper trading account. 
    - **BE CERTAIN TO RECORD YOUR PAPER TRADING ACCOUNT NUMBER, USERNAME AND PASSWORD**.
    This information will display in a yellow box after you submit the form.
    - You must complete this step and create a new paper trader even if you
    already have a paper trading account with IBKR.
5. Wait. It takes about **one business day** for your paper trading account
to activate -- most of that time is due to obtaining your permissions for market
data subscriptions from the various exchanges.
6. Visit the [Getting Started](https://gothic-hedge-society.github.io/fintech.trading.competition/articles/fintech-trading-competition.html) 
page. Install TWS and explore the Demo account for a bit while you wait for your
account to activate.
7. Once it's active, you will be able to log in to your paper trader using the
credentials from **Step 4**. Your username will be a simple alphanumeric string
like "jakev9914". Test that your account is live by logging in to TWS.
8. Check the [Registry](https://gothic-hedge-society.github.io/fintech.trading.competition/articles/Registry.html)
to confirm that the tradername you've chosen appears alongside the correct
account number of your paper trader.
9. Once your tradername appears alongside your paper trader's account number,
you're all set! You're encouraged to say 'hi' in the Slack channel.

# Rules
1. The competition will begin on Wednesday, 19 Jan 2022 at 9:30am EST.
2. The competition will end on Wednesday, 13 Apr 2022 at 4pm EST.
3. You can begin making trades as soon as you like, but only your end-of-day
portfolio values within these dates (inclusive) will be used for scoring.
Because the competition is scored based on Sharpe Ratio, it doesn't matter if
different participants begin the competition with different positions and cash.
4. If your account isn't activated by the start of the competition, then you
aren't eligible to participate so be sure to activate early!
5. Scoring will be based on Sharpe Ratio (highest wins). Please see the
following pages for more detailed information:
    - [Scoring](https://gothic-hedge-society.github.io/fintech.trading.competition/articles/Scoring.html) 
      basic idea
    - [Sharpe Ratio Calculation](https://gothic-hedge-society.github.io/fintech.trading.competition/articles/Sharpe%20Ratio%20Calculation.html)
6. **No account resets are allowed**. Be sure that any orders you make on your
trading account are what you want -- use the Demo account features for practice.
7. **You must make one trade during the first week**. If you don't trade during
the first week, your account will be deleted, your tradername will be removed
from the Registry and from the Slack channel, and a "dropout" note will be added
to your University. If you don't want to trade during the first week, then
simply make a small trade such as buying one share of the many 'penny stocks'
available for $5 USD or less to satisfy this requirement. If you can't access
your account, ask for help on the Slack channel.
