---
title: "Announcement"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Announcement}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo = FALSE}
shiny::tagList(
  shiny::fluidRow(
    shiny::fluidRow(
      shiny::column(width = 6, shiny::p("27 Jan 2022", class = "article-date")),
      shiny::column(
        width = 6,
        shiny::p(
          shiny::a(
            "Link to Official Announcement",
            href="https://fintech.meng.duke.edu/news/duke-fintech-intercollegiate-trading-competition-kicks-spring-2022"
          ),
          class = "original-article-link"
        ),
      )
    ),
    shiny::p(
      "Duke FinTech Annual InterCollegiate\n\nTrading Competition",
      class = "announcement-title"
    )
  ),
  shiny::fluidRow(
    shiny::p(
      paste0(
        "The annual trading competition sponsored by Duke’s Master of ",
        "Engineering in FinTech program kicked off this month, supported by ",
        "some extraordinary companies."  
      ),
      class = "subtitle"
    )
  ),
  shiny::fluidRow(
    style = "display: flex; align-items: center; justify-content: center;",
    shiny::column(
      width = 4, 
      shiny::a(shiny::img(src = "finvc_logo.png"), href = "https://finvc.co/")
    ),
    shiny::column(
      width = 4, 
      shiny::a(shiny::img(src = "horizen_logo.png"), href = "https://www.horizen.io/")
    ),
    shiny::column(
      width = 4,
      shiny::a(shiny::img(src = "mesh_logo.png"), href = "https://mesh.xyz/")
    )
  ),
  shiny::fluidRow(
    shiny::p(
      paste0(
        "This month, Duke FinTech kicked off the Annual Duke FinTech Intercollegiate Trading Competition—welcoming over 150 students from 40 different universities across the globe to compete against their peers for cash prizes and, perhaps most importantly, internationally recognized bragging rights."
      ),
      class = "basic-text"
    )
  ),
  shiny::fluidRow(
    shiny::p(
      shiny::span(
        paste0(
          "The trading competition gives graduate and undergraduate students an opportunity to apply what they are learning in the classroom and try out investment strategies using real-time market data and the same user interface and features utilized by professional traders. Over the course of the competioin, students will make trades in an effort to grow their inital portfolio of $1 million USD in simulated currency.  Trades are made in paper trading accounts provided by the "
        ),
        class = "basic-text"
      ),
      shiny::a(
        "Student Trading Lab", 
        href = "https://www.interactivebrokers.com/en/accounts/educator.php",
        class = "basic-link"
      ),
      shiny::span(
        " at Interactive Brokers, allowing students the ability to trade in all of the listed asset classes that one might expect, as well as cryptocurrencies.",
        class = "basic-text"
      )
    )
  ),
  shiny::fluidRow(
    shiny::p(
      shiny::span(
        "This year’s competition is led again by Professor Jake Vestal, Adjunct Assistant Professor in the Pratt School of Engineering, who sees the competition as much as a teaching tool as it is a contest.\""
      ),
      shiny::span(
        "This competition is special because in puts one of the Duke FinTech Program’s core values into practice: the taking on of risk (unavoidable in any endeavor) in a disciplined, well-reasoned manner,",
        class = "quote"
      ),
      shiny::span("\" shared Vestal. \""),
      shiny::span(
        "Our competition recognizes that being able to correctly predict 8 coin tosses in a row is a ‘skill’ that one out of 256 student traders possesses. Instead of declaring that one lucky trader the winner, Duke FinTech believes in rewarding acuity over gambling by ranking student traders according to their risk adjusted return (Sharpe Ratio) as opposed to simple realized return.",
        class = "quote"
      ),
      shiny::span(
        "\" This approach encourages shrewd investing and provides students with the opportunity to test out their own unique strategies, quantitative algorithms, and other methodologies."
      )
    ),
    class = "basic-text"
  ),
  shiny::fluidRow(
    shiny::p(
      shiny::span(
        "This year, competition prizes will be awarded in both USD and "
      ),
      shiny::a(
        "ZEN", 
        href = "https://www.horizen.io/",
        class = "basic-link"
      ),
      shiny::span(
        " cryptocurrency, thanks to support from some extraordinary companies!",
      ),
      class = "basic-text"
    )
  ),
  shiny::fluidRow(
    shiny::p(
      "This year, represented schools include:",
      class = 'table-header'
    )
  ),
  shiny::fluidRow(
    shiny::column(
      width = 6,
      shiny::p('Beijing University of Technology', class = 'school-name'),
      shiny::p('Boston University', class = 'school-name'),
      shiny::p('Carnegie Mellon University', class = 'school-name'),
      shiny::p('Case Western Reserve University', class = 'school-name'),
      shiny::p('Claremont Graduate University', class = 'school-name'),
      shiny::p('Colorado College', class = 'school-name'),
      shiny::p('Cornell University', class = 'school-name'),
      shiny::p('Duke University', class = 'school-name'),
      shiny::p('Georgetown University', class = 'school-name'),
      shiny::p('Georgia Institute of Technology', class = 'school-name'),
      shiny::p('Grinnell College', class = 'school-name'),
      shiny::p('Harvard University', class = 'school-name'),
      shiny::p('Hunan University', class = 'school-name'),
      shiny::p('Nanyang Technological University', class = 'school-name'),
      shiny::p('New York University', class = 'school-name'),
      shiny::p('North Carolina State University', class = 'school-name'),
      shiny::p('Northeastern University', class = 'school-name'),
      shiny::p('Princeton University', class = 'school-name'),
      shiny::p('Rutgers University', class = 'school-name'),
      shiny::p('School of Visual Arts', class = 'school-name')
    ),
    shiny::column(
      width = 6,
      shiny::p('Shanghai Jiao Tong University', class = 'school-name'),
      shiny::p('Shenzhen University', class = 'school-name'),
      shiny::p('Southern University of Science and Technology', class = 'school-name'),
      shiny::p('Texas A&M University', class = 'school-name'),
      shiny::p('The University of Chicago', class = 'school-name'),
      shiny::p('University of California, Los Angeles', class = 'school-name'),
      shiny::p('University of California, San Diego', class = 'school-name'),
      shiny::p('University of California, Santa Barbara', class = 'school-name'),
      shiny::p('University of Georgia', class = 'school-name'),
      shiny::p('University of Hawaii', class = 'school-name'),
      shiny::p('University of Michigan', class = 'school-name'),
      shiny::p('University of North Carolina at Chapel Hill', class = 'school-name'),
      shiny::p('University of North Carolina at Charlotte', class = 'school-name'),
      shiny::p('University of Rochester', class = 'school-name'),
      shiny::p('University of South Carolina', class = 'school-name'),
      shiny::p('University of Southern California', class = 'school-name'),
      shiny::p('University of Texas at Austin', class = 'school-name'),
      shiny::p('Vanderbilt University', class = 'school-name'),
      shiny::p('Washington University in St. Louis', class = 'school-name'),
      shiny::p('Xi\'an Jiaotong-Liverpool University', class = 'school-name')
    )
  )
)

```

```{r, echo = FALSE}
shiny::img(src = "horizen_logo_round.png", class="dont-show")
```

```{css, echo = FALSE}
h1, .dont-show {
display: none;
}

.announcement-title {
text-align: center;
font-size: 54px;
margin-top: 30px;
color: #FFD960;
}

.basic-text{
padding-top:10px;
padding-bottom:10px;
}

.basic-link, .basic-text, .quote{
font-size:18px;
}

.school-name{
color: Cornsilk;
font-size:19px;
}

.subtitle{
color:#bdd9d9;
font-size:25px;
font-style:italic;
text-align:center;
}

.article-date{
padding-top:10px;
text-align:left;
font-weight:bold;
color:#FCF7E5;
}

.original-article-link{
padding-top:10px;
text-align:right;
}

.quote {
color:#FCF7E5;
}

.table-header {
color:#FFD960;
font-size:22px;
}

```

