---
title: "Become a Sponsor"
output: html_document
---

```{r setup, include = FALSE}
library(magrittr)
```

We're thrilled that you're visiting our Sponsors page! Sponsors like you can 
benefit from our Competition's success in many ways:

  - **Donating funds**: We add donations to our overall cash prize awards which,
    of course, is a major motivator for attracting top performing traders to 
    the Competition. Therefore when you donate to us, you realize direct, 
    tangible returns by choosing to interview our traders for positions 
    at your firm.
  - **Interviewing our traders**: We'd love for you to agree to offer job 
    interview top performers for finance positions. Doing so will certainly 
    drive interest in the Competition, and you might very well find a diamond 
    that you otherwise would miss!
  - **Participating in our YouTube shows**: We'll recording 15-20 minute video
    chats with our sponsors this year on Comp & Coin, the [Competition's 
    companion YouTube channel](https://www.youtube.com/@DukeFintechCompetition).
    You can shoot one of these segments with us and use it to advertise job 
    openings, new products / initiatives, or simply show up and discuss markets.
  - **Participating in our Discord server**: Partner & Magnate level sponsors
    will have the option to access our Discord server and interact with the
    student traders directly -- something we certainly encourage!
    
Please fill out the form below and Zoe or Jake will reach out to you at the 
email you provided to discuss our collaboration! 

Thank you!!!!

# Benefits
We offer four levels of sponsorship, which receive benefits as described below:

## "Analyst" Tier ($2K -$5k):
- Logo featured on the Trading Competition's website as a link to your company's
  main website
- Company shoutout at the end of weekly Competition update videos (Listed in our
  “thank you to our sponsors”)
  
## "Managing Director" Tier ($5k -$10k):
- Logo featured on the Trading Competition's website as a link to your company's
  main website
- Company shoutout at the end of weekly Competition update videos (Listed in our
  “thank you to our sponsors”)
- Your company’s spokesperson (or several) appear as guests on “Comp & Coin”, 
  the Competition’s companion YouTube series
  
## "Partner" Tier ($10K -$25k):
- Logo featured on the Trading Competition's website as a link to your company's
  main website
- Company shoutout at the end of weekly Competition update videos (Listed in our
  “thank you to our sponsors”)
- Your company’s spokesperson (or several) appear as guests on “Comp & Coin”, 
  the Competition’s companion YouTube series
- 1 registration at [TechConnect](https://pratt.duke.edu/corporate/techconnect) recruiting event
- 1 parking pass
- Access to trader resumes
- Access to Recruiters channels on the Trading Competition's Discord server
  
## "Magnate" Tier ($25K+):
- Logo featured on the Trading Competition's website as a link to your company's
  main website
- Company shoutout at the end of weekly Competition update videos (Listed in our
  “thank you to our sponsors”)
- Your company’s spokesperson (or several) appear as guests on “Comp & Coin”, 
  the Competition’s companion YouTube series
- 1 registration at [TechConnect](https://pratt.duke.edu/corporate/techconnect) recruiting event
- 2 parking pass
- Access to trader resumes
- Unfettered access to the Trading Competition's Discord server, which you can
  use to interact with our traders (including voice chat)
- Meeting with Prof. Jimmie Lenz (Director of the FinTech Program) and Duke 
  FinTech Program faculty and staff 
- Access to trade-level data & financials of our student traders. 
  

<div id="wufoo-div" style="background-color:#fff;border-style:ridge;">
<div id="wufoo-w7u9gcl1niqvtm"> Fill out my <a href="https://dukefinance.wufoo.com/forms/w7u9gcl1niqvtm">online form</a>. </div> <script type="text/javascript"> var w7u9gcl1niqvtm; (function(d, t) { var s = d.createElement(t), options = { 'userName':'dukefinance', 'formHash':'w7u9gcl1niqvtm', 'autoResize':true, 'height':'1045', 'async':true, 'host':'wufoo.com', 'header':'show', 'ssl':true }; s.src = ('https:' == d.location.protocol ?'https://':'http://') + 'secure.wufoo.com/scripts/embed/form.js'; s.onload = s.onreadystatechange = function() { var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return; try { w7u9gcl1niqvtm = new WufooForm(); w7u9gcl1niqvtm.initialize(options); w7u9gcl1niqvtm.display(); } catch (e) { } }; var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr); })(document, 'script'); </script></div>
