---
title: "Reference Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reference Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE, echo=FALSE}
devtools::load_all(".")
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{css, echo=FALSE}
.dt-button {
color: greenyellow;
font-style: bold;
}
```

Here is the reference data used in the scoring. Feel free to use the buttons to
download this info for your own analysis!

```{css, echo=FALSE}
button.dt-button {
font-size: 14px;
color: greenyellow;
border: 1px solid white;
}
```

```{r echo=FALSE}
ref_data %>%
  dplyr::mutate(
    '3_mo' = .$`3_mo`/100
  ) %>%
  DT::datatable(
    .,
    extensions = c('Scroller', 'Buttons'),
    rownames   = FALSE,
    options = list(
      columnDefs   = list(list(className = 'dt-center', targets = '_all')),
      initComplete = DT::JS(
        "
      function(settings, json) {
          $(this.api().table().header()).css({
              'font-size' : '20px', 
              'color' : 'greenyellow'
          });
      }
      "
      ),
      dom         = 'Bt',
      buttons     = c('csv', 'excel', 'copy'),
      deferRender = TRUE,
      ordering    = FALSE,
      scrollY     = 500,
      scroller    = TRUE
    )
  ) %>%
  DT::formatPercentage('3_mo', 2)
```


