---
title: "Scoreboard"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Scoreboard}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
devtools::load_all('.')
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(knitr.table.format = "html") 
```

```{css, echo = FALSE}
button.dt-button {
font-size: 14px;
color: greenyellow;
border: 1px solid white;
}
.dataTables_filter label{
font-size: 18px;
color: greenyellow;
}
h1, h2 {
text-align: center;
}
.intro-text {
font-size: large;
color: beige;
text-align: center;
padding-top:12px;
padding-bottom:12px;
}
.fp-title, .ee-title {
font-size: x-large;
color: white;
text-align: center;
font-weight: bold;
}
.fp-tradername {
padding-top: 16px;
font-size: xx-large;
color: greenyellow;
text-align: center;
font-weight: bold;
}
.fp-school {
font-size: x-large;
text-align: center;
}
.fp-country {
font-size: x-large;
text-align: center;
}
.fp-sharpe {
font-size: x-large;
text-align: center;
}
.update-info-row {
font-size: x-large;
text-align: center;
font-weight: bold;
}
.last-updated-time{
color: greenyellow;
}
.leaderboard {
border-style: solid;
border-color: #FFD960;
}

.dygraph-legend {
width: auto !important;
min-width: 150px;
color: white;
background-color: #BABABA !important;
padding-left:5px;
border-color:#BABABA;
border-style:solid;
border-width:thin;
transition:0s 4s;
z-index: 80 !important;
box-shadow: 2px 2px 5px rgba(0, 0, 0, .3);
border-radius: 3px;
}

.dygraph-legend:hover{
transform: translate(-110%);
transition: 0s;
}

.dygraph-legend > span {
color: black;
padding-left:5px;
padding-right:2px;
margin-left:-5px;
background-color: white !important;
display: block;
}

.dygraph-legend > span:first-child {
margin-top:2px;
}

.dygraph-legend > span > span{
display: inline;
}

.highlight {
border-left: 2px solid #BABABA;
padding-left:3px !important;
}

.dygraph-ylabel {
color: greenyellow;
}

```

```{r echo=FALSE}
n_traders <- 10

shiny::tagList(
  shiny::fluidRow(
    shiny::tags$p(
      shiny::tags$span(
        "Last Updated: ", 
        class = "last-updated"
      ),
      shiny::tags$span(
        lubridate::with_tz(Sys.time(), tzone = "EST"), 
        class = "last-updated-time"
      ),
      class = "update-info-row"
    )  
  ),
  shiny::fluidRow(
    style = "display: flex; align-items: center; justify-content: center;",
    shiny::column(
      width = 4, 
      shiny::a(shiny::img(src = "finvc_logo.png"), href = "https://finvc.co/")
    ),
    shiny::column(
      width = 4, 
      shiny::a(shiny::img(src = "horizen_logo.png"), href = "https://www.horizen.io/")
    ),
    shiny::column(
      width = 4,
      shiny::a(shiny::img(src = "mesh_logo.png"), href = "https://mesh.xyz/")
    )
  ),
  shiny::fluidRow(
    shiny::tags$p(
      paste0(
        "Analysis of the 2022 Duke FINTECH Spring Trading Competition is ",
        "posted here. This section is frequently updated and expanded, so be",
        " sure to check back often. Don't forget to check out our generous ",
        "sponsors who made it all possible! Visit their websites by clicking ",
        "on the logos above."
      ),
      class = "intro-text"
    )  
  ),
  shiny::fluidRow(
    shiny::column(
      width = 6, 
      shiny::fluidRow(
        shiny::column(
          width = 9,
          shiny::p("First Place", class = "fp-title"),
          shiny::p(standings[1,'tradername'], class = "fp-tradername"),
          shiny::p(standings[1,'school'], class = "fp-school"),
          shiny::p(standings[1,'country'], class = "fp-country"),
          shiny::p(
            paste0("Sharpe: ", signif(standings[1,'Sharpe'], 5)), 
            class = "fp-sharpe"
          ),
        )
      )
    ),
    shiny::column(
      width = 6, 
      shiny::p("Runner-Ups", class = "ee-title"),
      shiny::HTML(
        standings[2:5,] %>%
          dplyr::mutate(
            "Sharpe" = signif(Sharpe, 5)
          ) %>%
          kableExtra::kbl(align="rcccc") %>%
          kableExtra::kable_minimal() %>%
          kableExtra::row_spec(
            0, color = "greenyellow"
          ) %>%
          kableExtra::column_spec(
            1,
            extra_css = "font-weight:bold; color:#FFD960;"
          ) %>%
          kableExtra::column_spec(
            1:5,
            extra_css = "vertical-align:middle;"
          )
      )
    ),
    class = "leaderboard"
  )
)
```

# Top Sharpe Ratios Over Time

```{r echo=FALSE}
sharpes %>%
  dplyr::select(
    Date,
    sharpes[nrow(sharpes),-1] %>% 
      unlist() %>%
      sort(decreasing = TRUE) %>% 
      head(n_traders) %>%
      names()
  ) %>% {
    
    x <- .
    
    padding_row_1 <-  stats::setNames(
      rep(NA_integer_, n_traders), 
      colnames(x)[-1]
    ) %>%
      tibble::as_tibble_row() %>%
      tibble::add_column("Date" = x$Date[1] - 1) %>%
      dplyr::select(colnames(x))
    
    padding_row_2 <-  stats::setNames(
      rep(NA_integer_, n_traders), 
      colnames(x)[-1]
    ) %>%
      tibble::as_tibble_row() %>%
      tibble::add_column("Date" = x$Date[nrow(x)] + 1) %>%
      dplyr::select(colnames(x))
    
    padding_row_1 %>%
      dplyr::bind_rows(x) %>%
      dplyr::bind_rows(padding_row_2)
    
  } %>%
  unique() %>%
  tibble::column_to_rownames("Date") %>%
  xts::as.xts() %>%
  dygraphs::dygraph(width = "100%") %>%
  dygraphs::dyOptions(
    strokeWidth            = 3,
    drawPoints             = TRUE, 
    pointSize              = 7,
    connectSeparatedPoints = TRUE
  ) %>%
  dygraphs::dyAxis(
    "y", 
    label             = "Sharpe Ratio",
    logscale          = TRUE,
    axisLabelFontSize = 16,
    axisLabelColor    = "#FFD960",
    axisLineWidth     = 3,
    axisLineColor     = "#E89923",
  ) %>%
  dygraphs::dyAxis(
    "x", 
    axisLabelFontSize = 16,
    axisLabelColor    = "#FFD960",
    axisLineWidth     = 3,
    axisLineColor     = "#E89923"
  ) %>%
  dygraphs::dyLegend(show = "follow") %>% {
    shiny::tagList(
      shiny::fluidRow(
        shiny::p("Mouse over the figure below for trader-level data."),
        style = "text-align:center;"
      ),
      shiny::fluidRow(
        shiny::column(width = 12, . )  
      )
    ) 
  }
```

# Top Returning Portfolios Over Time

```{r echo=FALSE}
cumulative_eod_excess_returns %>%
  dplyr::select(
    Date,
    cumulative_eod_excess_returns[nrow(cumulative_eod_excess_returns),-1] %>%
      unlist() %>%
      sort(decreasing = TRUE) %>%
      head(n_traders) %>%
      names()
  ) %>% {
    
    x <- .
    
    padding_row_1 <-  stats::setNames(
      rep(NA_integer_, n_traders),
      colnames(x)[-1]
    ) %>%
      tibble::as_tibble_row() %>%
      tibble::add_column("Date" = x$Date[1] - 1) %>%
      dplyr::select(colnames(x))
    
    padding_row_2 <-  stats::setNames(
      rep(NA_integer_, n_traders),
      colnames(x)[-1]
    ) %>%
      tibble::as_tibble_row() %>%
      tibble::add_column("Date" = x$Date[nrow(x)] + 1) %>%
      dplyr::select(colnames(x))
    
    padding_row_1 %>%
      dplyr::bind_rows(x) %>%
      dplyr::bind_rows(padding_row_2)
    
  } %>%
  unique() %>%
  tibble::column_to_rownames("Date") %>%
  xts::as.xts() %>%
  dygraphs::dygraph(width = "100%") %>%
  dygraphs::dyOptions(
    strokeWidth            = 3,
    drawPoints             = TRUE,
    pointSize              = 7,
    connectSeparatedPoints = TRUE
  ) %>%
  dygraphs::dyAxis(
    "y",
    valueFormatter     = "function(v){return (v*100).toFixed(2) + '%'}",
    axisLabelFormatter = "function(v){return (v*100).toFixed(2) + '%'}",
    label              = "Cumulative EoD Excess Return (%/day)",
    axisLabelFontSize  = 16,
    axisLabelColor     = "#FFD960",
    axisLineWidth      = 3,
    axisLineColor      = "#E89923",
  ) %>%
  dygraphs::dyAxis(
    "x",
    axisLabelFontSize = 16,
    axisLabelColor    = "#FFD960",
    axisLineWidth     = 3,
    axisLineColor     = "#E89923"
  ) %>%
  dygraphs::dyLegend(show = "follow") %>% {
    shiny::tagList(
      shiny::fluidRow(
        shiny::p("Mouse over the figure below for trader-level data."),
        style = "text-align:center;"
      ),
      shiny::fluidRow(
        shiny::column(width = 12, . )
      )
    )
  }
```

# Lowest Vol Portfolios Over Time

```{r echo=FALSE}
cumulative_vol %>%
  dplyr::select(
    Date,
    cumulative_vol[nrow(cumulative_vol),] %>%
      unlist() %>%
      sort() %>%
      head(n_traders) %>%
      names()
  ) %>% {
    
    x <- .
    
    padding_row_1 <-  stats::setNames(
      rep(NA_integer_, n_traders),
      colnames(x)[-1]
    ) %>%
      tibble::as_tibble_row() %>%
      tibble::add_column("Date" = x$Date[1] - 1) %>%
      dplyr::select(colnames(x))
    
    padding_row_2 <-  stats::setNames(
      rep(NA_integer_, n_traders),
      colnames(x)[-1]
    ) %>%
      tibble::as_tibble_row() %>%
      tibble::add_column("Date" = x$Date[nrow(x)] + 1) %>%
      dplyr::select(colnames(x))
    
    padding_row_1 %>%
      dplyr::bind_rows(x) %>%
      dplyr::bind_rows(padding_row_2)
    
  } %>%
  unique() %>%
  tibble::column_to_rownames("Date") %>%
  xts::as.xts() %>%
  dygraphs::dygraph(width = "100%") %>%
  dygraphs::dyOptions(
    strokeWidth            = 3,
    drawPoints             = TRUE,
    pointSize              = 7,
    connectSeparatedPoints = TRUE
  ) %>%
  dygraphs::dyAxis(
    "y",
    valueFormatter     = "function(v){return (v*10000).toFixed(3) + '&#8241 '}",
    axisLabelFormatter = "function(v){return (v*10000).toFixed(1) + '&#8241 '}",
    label              = "Sample Standard Deviation of Daily Returns (vol)",
    axisLabelFontSize  = 16,
    axisLabelColor     = "#FFD960",
    axisLineWidth      = 3,
    axisLineColor      = "#E89923",
  ) %>%
  dygraphs::dyAxis(
    "x",
    axisLabelFontSize = 16,
    axisLabelColor    = "#FFD960",
    axisLineWidth     = 3,
    axisLineColor     = "#E89923"
  ) %>%
  dygraphs::dyLegend(show = "follow") %>% {
    shiny::tagList(
      shiny::fluidRow(
        shiny::p("Mouse over the figure below for trader-level data."),
        shiny::p(
          shiny::span("\""),
          shiny::span(shiny::HTML("&#8241"), style = "font-weight:bold;"),
          shiny::span("\""),
          shiny::span("is the "),
          shiny::a(
            "permyriad", 
            href = "https://en.wikipedia.org/wiki/Basis_point#Permyriad"
          ),
          shiny::span(
            "symbol, used here for convenience. One permyriad = 1 100th of a ", 
            "percent; i.e., 0.02% == 0.02"
          ),
          shiny::HTML("&#8241"),
          shiny::span(".")
        ),
        style = "text-align:center;"
      ),
      shiny::fluidRow(
        shiny::column(width = 12, . )
      )
    )
  }
```

# Top Portfolio Values Over Time

```{r echo=FALSE}
eod_account_value %>%
  dplyr::select(
    Date,
    eod_account_value[nrow(eod_account_value),-1] %>%
      unlist() %>%
      sort(decreasing = TRUE) %>%
      head(n_traders) %>%
      names()
  ) %>% {
    
    x <- .
    
    padding_row_1 <-  stats::setNames(
      rep(NA_integer_, n_traders),
      colnames(x)[-1]
    ) %>%
      tibble::as_tibble_row() %>%
      tibble::add_column("Date" = x$Date[1] - 1) %>%
      dplyr::select(colnames(x))
    
    padding_row_2 <-  stats::setNames(
      rep(NA_integer_, n_traders),
      colnames(x)[-1]
    ) %>%
      tibble::as_tibble_row() %>%
      tibble::add_column("Date" = x$Date[nrow(x)] + 1) %>%
      dplyr::select(colnames(x))
    
    padding_row_1 %>%
      dplyr::bind_rows(x) %>%
      dplyr::bind_rows(padding_row_2)
    
  } %>%
  unique() %>%
  tibble::column_to_rownames("Date") %>%
  xts::as.xts() %>%
  dygraphs::dygraph(width = "100%") %>%
  dygraphs::dyOptions(
    strokeWidth            = 3,
    drawPoints             = TRUE,
    pointSize              = 7,
    connectSeparatedPoints = TRUE
  ) %>%
  dygraphs::dyAxis(
    "y",
    valueFormatter     = "function(v){return '$' + (v/1000000).toFixed(2)}",
    axisLabelFormatter = "function(v){return '$' + (v/1000000).toFixed(2)}",
    label              = "Portfolio Value ($MM)",
    axisLabelFontSize  = 16,
    axisLabelColor     = "#FFD960",
    axisLineWidth      = 3,
    axisLineColor      = "#E89923",
  ) %>%
  dygraphs::dyAxis(
    "x",
    axisLabelFontSize = 16,
    axisLabelColor    = "#FFD960",
    axisLineWidth     = 3,
    axisLineColor     = "#E89923"
  ) %>%
  dygraphs::dyLegend(show = "follow") %>% {
    shiny::tagList(
      shiny::fluidRow(
        shiny::p("Mouse over the figure below for trader-level data."),
        style = "text-align:center;"
      ),
      shiny::fluidRow(
        shiny::column(width = 12, . )
      )
    )
  }
```

<!-- # Trader Correlations -->

<!-- ```{r echo = FALSE} -->



<!-- shiny::tagList( -->
<!--   shiny::fluidRow( -->
<!--     shiny::column( -->
<!--       width = 4,♣ -->
<!--       shiny::p( -->
<!--         "Top Positive Correlation", -->
<!--         class = "correl-section-heading" -->
<!--       ), -->
<!--       shiny::p( -->
<!--         paste0( -->
<!--           "These traders' returns are highly correlated -- when one does", -->
<!--           " well, so does the other." -->
<!--         ) -->
<!--       ) -->
<!--     ), -->
<!--     shiny::column( -->
<!--       width = 4, -->
<!--       shiny::p( -->
<!--         "Least Correlation", -->
<!--         class = "correl-section-heading" -->
<!--       ), -->
<!--       shiny::p( -->
<!--         paste0( -->
<!--           "These traders' returns have little to do with each other, ", -->
<!--           "probably because their strategies are quite different." -->
<!--         ) -->
<!--       ) -->
<!--     ), -->
<!--     shiny::column( -->
<!--       width = 4, -->
<!--       shiny::p( -->
<!--         "Top Inverse Correlation", -->
<!--         class = "correl-section-heading" -->
<!--       ), -->
<!--       shiny::p( -->
<!--         paste0( -->
<!--           "These traders' returns have a contrary relationship -- when one ", -->
<!--           "does well, the other one does not." -->
<!--         ) -->
<!--       ) -->
<!--     ) -->
<!--   ) -->
<!-- ) -->
<!-- ``` -->

# Full Ranking
```{r echo=FALSE}
standings %>%
  dplyr::select(-country) %>%
  tibble::column_to_rownames("Rank") %>%
  DT::datatable(
    .,
    extensions = c('Buttons', 'Responsive'),
    options = list(
      columnDefs   = list(
        list(className = 'dt-center', targets = '_all')
      ),
      initComplete = DT::JS(
        "
      function(settings, json) {
          $(this.api().table().header()).css({
              'font-size' : '20px', 
              'color' : 'greenyellow'
          });
      }
      "
      ),
      paging      = FALSE,
      dom         = 'Bft',
      buttons     = c('csv', 'excel', 'copy'),
      ordering    = FALSE,
      deferRender = TRUE,
      scrollY     = 200
    )
  ) %>%
  DT::formatSignif('Sharpe', 5)
```
