---
title: "sponsors"
output: html_document
---

```{r setup, include = FALSE}
library(magrittr)
```

We're thrilled that you're visiting our Sponsors page! Sponsors like you can 
benefit from our Competition's success in many ways:

  - **Donating funds**: We add donations to our overall cash prize awards which,
    of course, is a major motivator for attracting top performing traders to 
    the Competition. Therefore when you donate to us, you realize direct, 
    tangible returns by choosing to interview our traders for positions 
    at your firm.
  - **Interviewing our traders**: We'd love for you to agree to offer job 
    interview top performers for finance positions. Doing so will certainly 
    drive interest in the Competition, and you might very well find a diamond in
    the rough that you otherwise would miss!
  - **Participating in our YouTube shows**: We'll recording 15-20 minute video
    chats with our sponsors this year on Comp & Coin, the [Competition's 
    companion YouTube channel](https://www.youtube.com/@DukeFintechCompetition).
    You can shoot one of these segments with us and use it to advertise job 
    openings, new products / initiatives, or simply show up and discuss markets.
  - **Participating in our Discord server**: Partner & Magnate level sponsors
    will have the option to access our Discord server and interact with the
    student traders directly -- something we certainly encourage!
    
    
