---
title: "traderpage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{traderpage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

  
```{r, include = FALSE}
library(fintech.trading.competition)
library(crosstalk)
sd <- SharedData$new(
  reports %>% 
    tidyr::unnest(statement) %>%
    dplyr::select(date, rank, dplyr::everything()) %>%
    dplyr::rename(α = alpha, β = beta) %>%
    dplyr::arrange(trader_name, dplyr::desc(date))
)
page_length <- reports$statement %>%
  vapply(
    function(x){nrow(x)},
    numeric(1)
  ) %>%
  unique()
```

```{css, echo=FALSE}
th {
  background-color: #222 !important;
}
```


Use this page to obtain detailed information about an individual trader.



```{r echo=FALSE}
shiny::fluidRow(
  filter_select(
    id         = "trader", 
    label      = "Select Trader", 
    sharedData = sd, 
    group      = ~trader_name,
    multiple   = FALSE
  ),
  sd %>%
    DT::datatable(
      rownames = FALSE,
      extensions = 'FixedColumns',
      options = list(
        dom          = 't',
        scrollX      = TRUE,
        scrollY      = '350px',
        ordering     = FALSE,
        fixedColumns = TRUE,
        pageLength   = page_length,
        initComplete = DT::JS(
          "function(settings, json) {",
          "$(this.api().table().header()).css(",
          "{'color': 'greenyellow', 'background-color': '#222'});",
          "}"
        ),
        columnDefs = list(
          list(visible=FALSE, targets=c(2,3,4,6,8,11,12))
        )
      )
    ) %>%
    DT::formatCurrency(c('NAV', 'sp500_close')) %>%
    DT::formatPercentage(
      c('daily_return', 'sp500_return', 'gmrr', 'vol', 'α', 'excess_rtn'), 
      digits=4
    ) %>%
    DT::formatSignif(c('β', 'sharpe'), digits=4) %>%
    DT::formatStyle('date', color = 'goldenrod', backgroundColor = '#222') %>%
    DT::formatStyle(
      c(
        'rank', 'NAV', 'sp500_close', 'daily_return', 'sp500_return', 'gmrr',
        'vol', 'α', 'β', 'excess_rtn', 'sharpe'
      ),
      color    = '#f0f0f0',
      fontSize = '0.75em'
    )
)
```
