---
title: "DU5020579"
output: html_document
---

```{css, echo = FALSE}
h1 {
text-align: center;
}
```

```{r setup, include=FALSE}

devtools::load_all('.')

account_id <- "DU5020579"

trader_key_i <- which(trader_key$account_id == account_id) 

trader    <- trader_key$tradername[trader_key_i]
country   <- trader_key$country[trader_key_i]
school    <- trader_key$school[trader_key_i]
if(trader_key$undergrad[trader_key_i]){
  acad_stat <- "undergraduate"
} else {
  acad_stat <- "graduate"
}
program   <- trader_key_i %>%
  trader_key[., c("undergrad_major", "graduate_dept")] %>% {
    .[which(!is.na(.))]
  } %>%
  unlist(use.names = FALSE)
grad_yr   <- trader_key$graduation_year[trader_key_i]
status    <- trader_key$graduation_year[trader_key_i]

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(knitr.table.format = "html") 
```

---
title: `r trader`
---

```{r echo=FALSE}
shiny::fluidRow(
  shiny::column(
    width = 5,
    shiny::HTML(
      tibble::tibble(
        "info"  = c(
          "Account ID:", "Country:", "School:", "Academic Status:", "Program:", 
          "Graduation Year:"
        ),
        "value" = c(account_id, country, school, acad_stat, program, grad_yr)
      ) %>%
        kableExtra::kable(col.names = NULL) %>%
        kableExtra::kable_paper(full_width = F) %>%
        kableExtra::kable_styling(bootstrap_options = "condensed") %>%
        kableExtra::column_spec(
          1, 
          bold         = TRUE, 
          color        = "greenyellow",
          border_right = "1px solid; 
            border-right-width: 1px;
            border-right-color: #FFD960;
            border-right-style: solid;"
        )      
    )
  ) #,
  # shiny::column(
  #   width = 7,
  #   if(status == "active"){
  #     eod_account_value[,c("Date", trader)] %>% {
  #       
  #       x <- .
  #       n_traders <- 1
  #       
  #       padding_row_1 <-  stats::setNames(
  #         rep(NA_integer_, n_traders),
  #         colnames(x)[-1]
  #       ) %>%
  #         tibble::as_tibble_row() %>%
  #         tibble::add_column("Date" = x$Date[1] - 1) %>%
  #         dplyr::select(colnames(x))
  #       
  #       padding_row_2 <-  stats::setNames(
  #         rep(NA_integer_, n_traders),
  #         colnames(x)[-1]
  #       ) %>%
  #         tibble::as_tibble_row() %>%
  #         tibble::add_column("Date" = x$Date[nrow(x)] + 1) %>%
  #         dplyr::select(colnames(x))
  #       
  #       padding_row_1 %>%
  #         dplyr::bind_rows(x) %>%
  #         dplyr::bind_rows(padding_row_2)
  #       
  #     } %>%
  #       unique() %>%
  #       tibble::column_to_rownames("Date") %>%
  #       xts::as.xts() %>%
  #       dygraphs::dygraph(width = "100%") %>%
  #       dygraphs::dyOptions(
  #         strokeWidth            = 3,
  #         drawPoints             = TRUE,
  #         pointSize              = 7,
  #         connectSeparatedPoints = TRUE
  #       ) %>%
  #       dygraphs::dyAxis(
  #         "y",
  #         valueFormatter     = "function(v){return '$' + (v/1000000).toFixed(3)}",
  #         axisLabelFormatter = "function(v){return '$' + (v/1000000).toFixed(2)}",
  #         label              = "Portfolio Value ($MM)",
  #         axisLabelFontSize  = 16,
  #         axisLabelColor     = "#FFD960",
  #         axisLineWidth      = 3,
  #         axisLineColor      = "#E89923",
  #       ) %>%
  #       dygraphs::dyAxis(
  #         "x",
  #         axisLabelFontSize = 16,
  #         axisLabelColor    = "#FFD960",
  #         axisLineWidth     = 3,
  #         axisLineColor     = "#E89923"
  #       ) 
  #   }
  # )
)
```


