---
title: "Rules"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Rules}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Rule 1: Registration
1. Registration ENDS on Wednesday, 19 Jan 2022 at 9:30am EST. No new
participants may sign up after that date except under extenuating circumstances.

## Rule 2: Competition Start
1. The '**start**' of the Competition is taken to mean '**the first day upon
which participants' end-of-day account values will be tracked and used for
scoring and ranking**'.
2. The **start date** will be selected by **The Architect ** as **the earliest
date on which all IBKR paper trader accounts created by '**good faith
participants**' have become active and ready to trade**.
    - Since it can take a day or two for everyone's paper trading accounts to come
fully online and active, it's difficult to pin down an exact start date in advance
    - **The Architect** will use the
    [Registry](https://gothic-hedge-society.github.io/fintech.trading.competition/articles/registry.html)
    to make a best-effort determination of the start date
    - The start date will be announced as soon as possible by email, on Slack,
    and on the website
    - Note that, because participants are scored and ranked
by [Sharpe
Ratio](https://gothic-hedge-society.github.io/fintech.trading.competition/articles/Scoring.html),
the exact 'start date' shouldn't really matter much in the first place, but it's
important for the Competition to be methodical about this in the event of a
close tie.
3. **'Good faith participants'** means those participants who filled out and submitted their IBKR Paper Trader forms as soon as they were able.
4. **'Good faith participants'** does **not** mean those participants who never
bothered to:
    - submit their paper trader forms promptly
    - read their Competition email updates and take appropriate action
    - DM **The Architect** on Slack to ask for help with any technical issues 

## Rule 3: Competition End
1. The Competition will end on **Wednesday, 13 Apr 2022 at 4pm EST**.
2. Your end-of-day mark-to-market portfolio value on **Wednesday, 13 Apr 2022**
**will** be included in the final scoring.

## Rule 4: Non-Participants
1. Participants who have not made a complete, round-trip trade by the 
**Paper Trader Cutoff Date** are considered "**non-participating traders**".
2. Non-participating traders are welcome to trade all they want. Their info and 
traderpages will continue to be tracked and updated, but they won't be included 
trading competition scoreboards and they are not eligible for prizes.

## Rule 5: Scoring
1. Scoring will be based on Sharpe Ratio (highest wins). Please see the
following pages for more detailed information:
    - [Scoring](https://gothic-hedge-society.github.io/fintech.trading.competition/articles/Scoring.html) 
      basic idea
    - [Sharpe Ratio Calculation](https://gothic-hedge-society.github.io/fintech.trading.competition/articles/Sharpe%20Ratio%20Calculation.html)
2. Your Sharpe ratio will be calculated using all data available from the start 
date onwards; in other words, it might be best for you to start trading as soon 
as you can so that you don't have a lot of 0% return days at the beginning of 
the competition dragging down your overall return.

    
## Rule 6: No Account Resets 
1. Account resets will not be allowed in this competition.
2. Be sure that any orders you make on your trading account are what you really
want -- use the Demo account for practice.

## Rule 7: Pruning of Old / Unwanted Accounts
1. **You must make at least one trade per month**; otherwise, your account will
be considered unwanted and will be deleted.
2. If this happens, you're welcome to make a new account at any time.

## Rule 8: When in Doubt, Ask **The Architect**
1. It is your responsibility to contact **The Architect** on Slack with any
questions, concerns, or techical issues you have in as prompt a fashion as you
are able.

## Rule 9: Teams are Allowed
1. You can work by yourself or with others. Be sure to figure out how you're
going to split up your prize money ahead of time if you win!

## Rule 10: Trade Whatever you Want
1. Anything that is tradable within your system is valid for the Competition.
